apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: genai-photo-generator-app-dev
  annotations:
    argocd/app-name: genai-photo-generator-app-dev
    backstage.io/kubernetes-id: genai-photo-generator-app
    backstage.io/kubernetes-namespace: genai
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: WindTurbineInc/genai-photo-generator
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/dev-pipelines/ns/genai/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/k8s/ns/genai/deployments/genai-photo-generator-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.wearedevs.rl97.p1.openshiftapps.com/#https://github.com/WindTurbineInc/genai-photo-generator?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/blues-man"
  consumesApis:
  - photo-generator-genai

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: photo-generator-genai
  description: API invoked to create images of Red Hat Teddy
  links:
    - url: https://editor.swagger.io/
      title: Swagger UI
      icon: web
    - url: https://github.com/WindTurbineInc/software-templates/blob/master/scaffolder-templates/wheres-teddy/skeleton/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/blues-man"
  definition:
    $text: https://github.com/WindTurbineInc/software-templates/blob/master/scaffolder-templates/wheres-teddy/skeleton/openapi.yaml
